name: Result Service Sysdig Scan

on:
  # Run when image is built and pushed
  workflow_run:
    workflows: ["Build Result"]
    types:
      - completed
    branches:
      - main

env:
  SYSDIG_SECURE_ENDPOINT: "https://eu1.app.sysdig.com"
  REGISTRY_HOST: "ghcr.io"
  IMAGE_NAME: "alexgoller/example-voting-app-result"
  IMAGE_TAG: "latest"

jobs:
  sysdig-scan:
    name: Sysdig Secure Scan
    runs-on: ubuntu-latest
    # Only run if the build workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      security-events: write  # needed for uploading SARIF results
      actions: read           # needed for workflow_run trigger
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Updated to v4
      
      - name: Scan image with Sysdig
        id: scan
        uses: sysdiglabs/scan-action@v5
        with:
          # Image to scan
          image-tag: ${{ env.REGISTRY_HOST }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          
          # Sysdig configuration
          sysdig-secure-token: ${{ secrets.SECURE_API_TOKEN }}
          sysdig-secure-url: ${{ env.SYSDIG_SECURE_ENDPOINT }}
          
          # Security configuration
          stop-on-failed-policy-eval: false  # Set to true if you want to fail the job on policy violations
          stop-on-processing-error: true     # Fail on scanner errors
          
          # Filtering and reporting options
          severity-at-least: "medium"        # Only report medium and above vulnerabilities
          group-by-package: true            # Group vulnerabilities by package in SARIF
          
          # Optional: Specify policies to evaluate (comma-separated)
          # policies: "policy-name-1,policy-name-2"
          
          # Optional: Custom pull string for better identification in Sysdig UI
          # override-pullstring: "${{ env.REGISTRY_HOST }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"

      - name: Upload SARIF file to GitHub Security
        uses: github/codeql-action/upload-sarif@v3  # Updated to v3
        if: always()  # Upload results even if scan fails
        with:
          sarif_file: ${{ github.workspace }}/sarif.json
          category: "sysdig-container-scan"    # Unique category to avoid conflicts
          
      - name: Upload scan results as artifact
        uses: actions/upload-artifact@v4
        if: always()  # Always upload for debugging
        with:
          name: sysdig-scan-results
          path: |
            ${{ github.workspace }}/sarif.json
            ${{ github.workspace }}/sysdig-scan-result.json
          retention-days: 30

      # Optional: Add a step to comment on PR with scan summary (for PR workflows)
      # - name: Comment PR with scan results
      #   if: github.event_name == 'pull_request' && always()
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       // Add custom logic to parse results and comment on PR
