# fix
name: Sysdig Security Scan
on:
  workflow_call:
    inputs:
      image-name:
        description: 'Full image name to scan'
        required: true
        type: string
      image-tag:
        description: 'Image tag to scan'
        required: true
        type: string
      registry-host:
        description: 'Registry host'
        required: false
        type: string
        default: 'ghcr.io'
      severity-threshold:
        description: 'Minimum severity level'
        required: false
        type: string
        default: 'medium'
    secrets:
      SECURE_API_TOKEN:
        required: true

env:
  SYSDIG_SECURE_ENDPOINT: "https://eu1.app.sysdig.com"

jobs:
  sysdig-scan:
    name: Sysdig Secure Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Scan image with Sysdig
        id: scan
        uses: sysdiglabs/scan-action@v5
        with:
          image-tag: ${{ inputs.registry-host }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
          sysdig-secure-token: ${{ secrets.SECURE_API_TOKEN }}
          sysdig-secure-url: ${{ env.SYSDIG_SECURE_ENDPOINT }}
          stop-on-failed-policy-eval: false
          stop-on-processing-error: true
          severity-at-least: ${{ inputs.severity-threshold }}
          group-by-package: true
          
      - name: Upload SARIF file to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: ${{ github.workspace }}/sarif.json
          category: sysdig-${{ inputs.image-name }}-scan
          
      - name: Upload scan results as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: sysdig-scan-results-${{ inputs.image-name }}-${{ inputs.image-tag }}
          path: |
            ${{ github.workspace }}/sarif.json
            ${{ github.workspace }}/sysdig-scan-result.json
          retention-days: 30
