name: Sysdig IaC Security Scan
on:
  push:
    branches: [main, develop]
    paths:
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.tf'
      - '**/*.json'
      - 'docker-compose*.yml'
      - 'k8s/**'
      - 'k8s-specifications/**'
      - 'kubernetes/**'
      - 'infrastructure/**'
      - 'terraform/**'
  pull_request:
    branches: [main, develop]  
    paths:
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.tf'
      - '**/*.json'
      - 'docker-compose*.yml'
      - 'k8s/**'
      - 'kubernetes/**'
      - 'infrastructure/**'
      - 'terraform/**'

env:
  SYSDIG_SECURE_ENDPOINT: "https://eu1.app.sysdig.com"

jobs:
  iac-scan:
    name: Infrastructure as Code Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Run Sysdig IaC Scanner
        uses: sysdiglabs/scan-action@v5
        with:
          # Enable IaC scanning mode
          mode: iac
          iac-scan-path: ./k8s-specifications
          
          # Sysdig configuration
          sysdig-secure-token: ${{ secrets.SECURE_API_TOKEN }}
          sysdig-secure-url: ${{ env.SYSDIG_SECURE_ENDPOINT }}
          
          # IaC specific settings
          stop-on-failed-policy-eval: false
          stop-on-processing-error: true
          
          # Output format and filtering
          severity-at-least: "medium"
          
          # Optional: specify which IaC frameworks to scan
          # iac-scan-frameworks: "terraform,kubernetes,cloudformation"
